services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY:-}
        NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:-}
        NEXT_PUBLIC_COOKIEBOT_ID: ${NEXT_PUBLIC_COOKIEBOT_ID:-}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    ports:
      - "127.0.0.1:3000:3000"